Update and rename main.yml to ci.yml
finished addin verification

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,3 +21,10 @@ jobs:
         
       - name: Install proj
         run: sudo make install
+      - name: verift install
+        run: |
+          if [ ! -f /usr/local/bin/your_binary ]; then
+            echo "Installation failed! :("
+            exit 1
+          fi 
+          echo "Installation succesful :)"
